### ISSUE TITLE
搜索设备出错

### ISSUE THREAD

**Issue by LuffYH** [PetterJong/android-onvif#2]
System.err: java.net.SocketTimeoutException: Poll timed out
System.err:     at libcore.io.IoBridge.poll(IoBridge.java:664)
System.err:     at java.net.PlainDatagramSocketImpl.doRecv(PlainDatagramSocketImpl.java:150)
System.err:     at java.net.PlainDatagramSocketImpl.receive0(PlainDatagramSocketImpl.java:141)
System.err:     at java.net.AbstractPlainDatagramSocketImpl.receive(AbstractPlainDatagramSocketImpl.java:162)
System.err:     at java.net.DatagramSocket.receive(DatagramSocket.java:847)
System.err:     at com.wp.android_onvif.onvif.FindDevicesThread.run(FindDevicesThread.java:85)

**Comment by PetterJong** [comment]
账号密码别搞错，sdk中我写死了，写错了会导致鉴权不通过。其次就以一下权限是否给了

**Comment by 15534408044** [comment]
我也发现了这个问题，java.net.SocketTimeoutException:Poll timed out
怀疑是while循环的时间太长，我用200ms试了一下，是可以了，不报这个错误了。
但在日本的手机上又出现这个错误了，现在怀疑是不是跟IPV4/V6有关，我也还在研究这个协议
作者给出的东西已经很赞了。还有一个坑是Canon摄像头不支持WS鉴权

**Comment by PetterJong** [comment]
理论上onvif协议应该都是要支持ws鉴权的，你可以问问厂家看。另外你可以试试http鉴权，这种方式也是可以的。你可以参考下我的博客https://blog.csdn.net/sinat_33285127/article/details/103024016，写的比较简单，希望对你有所帮助！~不过你说的那个Poll timed out的问题 我倒是没有碰到，我暂时也不知道如何解决

**Comment by 15534408044** [comment]
Poll timed out这个异常不影响设备发现，只是抛出了一个异常。但probe.xml里面的uuid你写死了，有些IPC（比如佳能、松下）相同的UUID设备只能被发现一次，所以最好还是随机生成。

**Comment by 15534408044** [comment]
按自己需求重新改造了一下http鉴权，也成功获取到了devicesInfo、profiles、Streamuri这些信息。
Poll Timed OUT这个异常我觉的是while循环时间太长，建议100-300ms就行，我目前是200ms,不出现这个异常

**Comment by PetterJong** [comment]
我心里想着 时间太短 怕某些设备来不及回应，哈哈哈。UUID这个我没有研究到那么细致，主要手上那么多设备，海康的还行，不过多谢你的建议

**Comment by MoYouenze** [comment]
请问有做onvif服务端的吗，我有一些问题，就是怎么实现http digest鉴权，还有rtsp的鉴权
